name: Build and push docker image

on: 
  push:
    branches : [ $default-branch ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build-and-push:
    uses: Eirbware/.github/.github/workflows/build-and-publish.yml@master
    with:
      file: "./Dockerfile"
      image_name: ${{ github.repository }}
    # registry_username and registry_api_key must be defined
    secrets: inherit
