name: Deploy static website

on: 
  push:
    branches : [ $default-branch ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  deploy:
    uses: Eirbware/.github/.github/workflows/deploy-static.yml@master
    # portainer_stack_webhook must be defined
    with: 
      remote_user: "www-eirb"
      directory_to_copy: "./dist"
    secrets: inherit
